### ISSUE TITLE
Provide config option to toggle the use of models

### ISSUE THREAD

**Issue by analogue** [Yelp/bravado-core#15]
Introduce a configuration option that toggles the use of models in incoming requests (server-side) and incoming responses (client side).  This is primarily for backwards compatibility with swagger-py 0.7.5 behavior.

When ```use_models``` is ```True```, references to ```#/definitions/{models}``` will be returned as model types. When ```False```, a dict will be used instead.

In ```bravado_core.spec```:

```python
CONFIG_DEFAULTS = {
    "use_models": True
    ...
}
```

**Comment by dnephin** [comment]
This is in master
