### ISSUE TITLE
$ref not automatically solved

### ISSUE THREAD

**Issue by Amedeo91** [Yelp/bravado-core#169]
I see that sometimes the $ref or the $allOf or $anyOf are automatically solve and I have to solve them manually in order to make it work. Why?

Example below:
{'x-scope': [''], 'additionalProperties': False, '$ref': '#/definitions/My_Resource'}

Regards,
Amedeo

**Comment by macisamuele** [comment]
Closing since duplicated in https://github.com/Yelp/bravado/issues/282
