### ISSUE TITLE
x-nullable doesn't work with objects

### ISSUE THREAD

**Issue by bxm156** [Yelp/bravado-core#170]
Example partial spec:
```
  responses:
    "200":
      description: example
      schema:
        type: object
        description: example
        properties:
          propA:
            description: something
            type: string
            x-nullable: true
          propB:
            description: this doesn't work
            $ref: ../../../objects/some_other_model.yaml
            x-nullable: true
        required:
          - propA
          - propB
``
I can set propA to None for my response, which is expected.
But I cannot set propB to None.

Error Output:
```
None is not of type 'object'
Failed validating 'type' in schema['properties']['propB']:
....
On instance['propB']:
    None
``

**Comment by sjaensch** [comment]
`required` and `x-nullable` are mutually exclusive. If a property needs to be present then it can't be `None`. We consider a `None` value to be the same as not sending a property at all. Remove `propB` from the list of required attributes and things will work as expected.
