### ISSUE TITLE
question on x-example extension use

### ISSUE THREAD

**Issue by markfink** [Yelp/bravado-core#180]
I am new to bravado and just starting so I would appreciate a pointer.

I would like to add a custom extension 'x-example' to my spec so I can create sample data / scaffolding data from my spec (similar to what DREDD does). Is that possible with bravado / docu
 / sample available?

thank you
Mark

**Comment by macisamuele** [comment]
@markfink bravado/bravado-core doesn't handle x-example attribute, if you set it in your specs it will not be used by those libraries.
If you're interested in having mocks of your endpoints you could have a look to https://github.com/Yelp/pyramid_mock_server/

**Comment by markfink** [comment]
thanks @macisamuele for your input. I found a recipe on how to parse the opanapi specs and extract the sample data from it (https://github.com/Trax-air/swagger-parser/blob/master/swagger_parser/swagger_parser.py). With a few tweaks this really rocks!
