### ISSUE TITLE
x-nullable working only for required properties of objects

### ISSUE THREAD

**Issue by janekbaraniewski** [Yelp/bravado-core#185]
Hey, I've stumbled upon an unexpected behaviour when using `x-nullable` 

My swagger definition:
```
...
        "SomeObject": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "required": [
                        "type"
                    ],
                    "properties": {
                        "type": {
                            "type": "string"
                        },
                        "attributes": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "string"
                                },
                                "nullable_field": {
                                    "type": "string",
                                    "x-nullable": true
                                }
                            }
                        }
                    }
                }
            }
        }
...
```
From what is stated in [bravado-core documentation](http://bravado-core.readthedocs.io/en/latest/models.html#allowing-null-values-for-properties) I should be able to send in my request `None` as a value of `nullable_field` but sadly that's not the case, `nullable_field` simply doesn't exist in the generated payload. 

I've traced the issue to `marshal_object` method, where if the value of the field is `None` and this field is not required, then the field is simply omitted. This is inconsistent with documentation, where there is no mention that field has to be a required field in order for this to work - even more, in example in documentation field that is being set to null is also not required.

If I'm right and this is a bug I'll be happy to submit PR with a fix, and if not could you explain why it is implemented in this way?

**Comment by macisamuele** [comment]
@janekbaraniewski I quickly checked the implementation of [``handle_null_value``](https://github.com/Yelp/bravado-core/blob/27ed3d16c9ba734ec177ea4c393afba515ba6334/bravado_core/schema.py#L127) and the result that you're getting seems correct according to the code.

From you're prospective this seems wrong and I agree with you. This is a bug.

I think that we have no tests for nullable properties that could be also not-required properties.

I would have no time until Monday/Tuesday to dig more in the code and publish a PR, but if you will be able to do prepare the PR it will be really appreciated.

**Comment by janekbaraniewski** [comment]
hey @macisamuele, thanks for the quick response.
Yeah, sure, I should have PR ready within few hours :)

**Comment by janekbaraniewski** [comment]
PR #186 is ready for review :)

**Comment by sjaensch** [comment]
Heh this is interesting. We've actually never intended for `x-nullable` to be used this way. It was always to allow bravado (as the client) to not complain about `null` values being sent from the server. That's why we have a [battery of tests](https://github.com/Yelp/bravado-core/blob/master/tests/unmarshal/unmarshal_object_test.py#L403) testing every possible case for unmarshalling.

I think it makes sense for marshalling too, so I'm all for it. I see that @macisamuele has just replied as I was writing this. :)

**Comment by janekbaraniewski** [comment]
Hey @macisamuele, just a followup to this issue, can you tell me when you plan to release those changes?

**Comment by macisamuele** [comment]
It's already released ;)

**Comment by janekbaraniewski** [comment]
awesome :D thanks!
