### ISSUE TITLE
marshalling/unmarshalling an array should support multiple schemas in `items`

### ISSUE THREAD

**Issue by desiam** [Yelp/bravado-core#230]
Currently, bravado does not support lists for the `items` key of a jsonschema array.
Bravado marshalling and unmarshalling assumes one schema applies to all items of an array. In the following link, `marshal_array` gets the value for the key, `items`, and calls `marshal_schema_object` on each item in the array with that schema.
- https://github.com/Yelp/bravado-core/blob/master/bravado_core/marshal.py#L112

The code will throw an exception if run against an array of values with different schemas. If `items_spec` is a list of schemas (for the items in the array), `marshal_schema_object` will result in an error when trying to perform `obj_type = schema_object_spec.get('type')`, because `schema_object_spec` is a `dict` and not a `list`. 
- https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation

If `is_list_like(item_spec)`, the 0th spec and the 0th value of `array_value` should be passed in together to `marshal_schema_object`...etc. An exception should be raised if `is_list_like(item_spec) and len(item_spec) != len(array_value)`

The same logic applies for unmarshalling.

**Comment by macisamuele** [comment]
@desiam you're right ... we do not have support for it.
Could you help us by providing a PR?

**Comment by macisamuele** [comment]
@desiam you're right we do not have support for it.
Checking the Swagger 2.0 specs ([link](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject)) I see that the content of ``items`` should be an object, so I guess that swagger does not support that.

**Comment by macisamuele** [comment]
As no objections after the last comment on November, I'm closing it.
