### ISSUE TITLE
Plans for OpenAPI v3.0 support

### ISSUE THREAD

**Issue by sobayed** [Yelp/bravado-core#233]
Hi there,

I'm curious whether there are any plans to add support for OpenAPI v3.0?

**Comment by sjaensch** [comment]
@sobayed there are no plans by the current maintainers to work on OpenAPI 3.0 support, however pull requests are very welcome, if you'd like to take a stab at it. :)

**Comment by advance512** [comment]
Hey there,

Any update?
Is anyone working on OpenAPI 3.0 support?

**Comment by sjaensch** [comment]
@advance512 nobody is working on it at the moment. Would you be interested in contributing in that direction?

**Comment by advance512** [comment]
@sjaensch 
Perhaps, we shall see how time is allocated in our engineering team. We're tiny, sadly.

Did Yelp leave OpenAPI altogether? Are you sticking with OpenAPI 2.0? Or are you using an alternative tool in-house?
