### ISSUE TITLE
how do i fix this warning 

### ISSUE THREAD

**Issue by ChrisJohannnesson** [Yelp/bravado-core#291]
Warning (from warnings module):
  File "C:\Python37\lib\site-packages\bravado_core\spec.py", line 271
    category=Warning,
Warning: JSON format is not registered with bravado-core!
([], <bravado.requests_client.RequestsResponseAdapter object at 0x000002424B7ECB00>)

**Comment by macisamuele** [comment]
Hello @ChrisJohannnesson, the warning that you reported is thrown in case the loaded swagger spec contains un-standard formats that are not handled via [User Defined Fromat](https://bravado-core.readthedocs.io/en/stable/formats.html).
Defining the UDF should remove your warning, but in general UDF are meant to add validation and conversions utilities for speicified types.

If you need additional support please provide a small snippet of the swagger spec and the python code, so it will be easier to help you.

---
UDF are useful to convert JSON data to a more manageble and easier to use python objects.
An example could be `format: date` for `type: string`.
A valid json representation of this type of object could be `"2018-07-27"`, thanks to the [defined UDF](https://github.com/Yelp/bravado-core/blob/v5.0.4/bravado_core/formatter.py#L112), it will be converted to `datetime.date(2018,7,27)`

**Comment by macisamuele** [comment]
Closing it as no responses are provided over 6 months
