### ISSUE TITLE
Travis build is failing on python2.7 after jsonschema 3.0.0 release

### ISSUE THREAD

**Issue by macisamuele** [Yelp/bravado-core#318]
Soon after `jsonschema==3.0.0` was released bravado-core tests are failing on Python 2.7 ([before](https://travis-ci.org/Yelp/bravado-core/jobs/497553696), [after](https://travis-ci.org/Yelp/bravado-core/jobs/497851981)).

We should fix tests as `bravado-core>= 5.10.0` should be able to support `jsonschema==3.0.0`

**Comment by macisamuele** [comment]
#319 was opened to address the issue.
Tests were red and @sjaensch already fixed it in #320.

@sjaensch do you think we're good to release a new version of the library?
This will be the first version with 100% compatibility with jsonschema>=3.0.0 (check #319 for more details)

**Comment by sjaensch** [comment]
The fix has been released in 5.10.2.
