### ISSUE TITLE
uuid format is not registered with bravado-core

### ISSUE THREAD

**Issue by mrmaxformax** [Yelp/bravado-core#376]
Hello,
Got the warning: "uuid format is not registered with bravado-core"
it's not critical issue but could you pls add the uuid not the next release?
I added it based on the description and the Warning gone but not sure if it is 100% correct. May I ask you to check and help to fix (if it is incorrect)
```python
class UUIDFormat:
    def __init__(self, uuid):
        self.uuid = uuid

def validate_uuid(uuid):
    try:
        UUID(uuid)
     except SwaggerValidationError:
         LOG.debug(f"UUID {uuid} is invalid")
         raise SwaggerValidationError

uuid_format = SwaggerFormat(format='uuid', 
    to_wire=lambda uuid_object: uuid_object.uuid,
    to_python=lambda uuid_str: UUIDFormat(uuid_str),
    validate=validate_uuid, description='validate UUID')
```

Thanks!

**Comment by sjaensch** [comment]
It looks correct to me, but you should be able to make sure it is correct by adding appropriate tests to your project.

**Comment by le91688** [comment]
Was UUID ever added? I get this warning using bravado 11.0.3
