### ISSUE TITLE
Also tag models with external references.

### ISSUE THREAD

**Issue by prat0318** [Yelp/bravado-core#45]
Currently only models present in `#/definitions` get tagged with `x-model: <model name>` and get used during marshalling/unmarshalling for type conversion to a python class versus a dict. Other models referred using `file://` or `http://` should also be treated in the same manner.

There can be cases where `$ref` refers to a complete file, like shown [here](https://github.com/swagger-api/swagger-spec/blob/master/guidelines/REUSE.md#definitions):
```json
{
  "description": "A simple model",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "tag": {
      "description": "a complex, shared property.  Note the absolute reference",
      "$ref": "https://my.company.com/definitions/Tag.json"
    }
  }
}
```
These kind of `ref`s can be ignored, as they do not contain a `Tag` name, to associate them with.

**Comment by analogue** [comment]
Fixed in 3.0.1
