### ISSUE TITLE
Add allow_null option

### ISSUE THREAD

**Issue by jpizarrom** [Yelp/bravado-core#47]
Add allow_null option like
https://github.com/Yelp/bravado-core/blob/632a0f9a9ec0a3fe5c996e932b01fec9a1c933d8/docs/source/quickstart.rst#advanced-options

**Comment by jpizarrom** [comment]
It's posible to use x-nullable like propose in https://github.com/swagger-api/swagger-spec/issues/229

The use of x-nullable respect the spec https://github.com/swagger-api/swagger-spec/blob/d79c205485d702302003d4de2f2c980d1caf10f9/versions/2.0.md#patterned-objects

example of a property
```
"next": {
  "type": "string",
  "x-nullable": true
 }
```

**Comment by jpizarrom** [comment]
https://github.com/admetricks/bravado-core/commit/9360ff2e7fcee14069b2f4b0ae267e3047901586

**Comment by andreashug** [comment]
This would be great. I'm using Swagger to build a client for a third-party API so changing it to match with the specification is not an option.

Would you accept a pull request with tests and documentation?

**Comment by analogue** [comment]
I'm a little concerned that the next version of the Swagger Spec will start to support this behavior but in a possibly different way.  Anyone know what the plans are for this feature in the working group?

Maybe @webron can chime in here?

**Comment by webron** [comment]
I'm afraid I don't have a clear answer to that as the official discussions haven't started. Right now, it's just the community chiming in. Haven't thoroughly investigated it, but it is possible we'll have a property that's `isNullable` or something like that which would default to either true or false.

**Comment by analogue** [comment]
@andreashug Feel free to submit a PR

**Comment by sjaensch** [comment]
This is fixed with the support for the property `x-nullable`.
