### ISSUE TITLE
Badly formatted string inputs cause ValueError instead of SwaggerMappingError

### ISSUE THREAD

**Issue by bwarfield-amplify** [Yelp/bravado-core#88]
Given a `string` value that has a `date-time` format, an incorrectly formatted input (say, "string") will cause `dateutil.parser.parse` to raise `ValueError: Unknown string format` when unmarshalling the request.  This isn't checked anywhere, so it bubbles up as an unexpected error, rather than being reported as invalid input.

It seems like the place to check this is in `unmarshal_primitive`: the call to [formatter.to_python](/Yelp/bravado-core/blob/master/bravado_core/unmarshal.py#L72) could be wrapped in a try block, with `ValueError` trapped and re-raised as a `SwaggerMappingError` (allowing callers to recognize this as a malformed request)—is that the right fix?

**Comment by laucia** [comment]
If this is happening just for date-time maybe we should instead update the formatter: https://github.com/Yelp/bravado-core/blob/master/bravado_core/formatter.py#L115

It would be interesting though to see why jsonschema is not picking a validation error in the first place

**Comment by bwarfield-amplify** [comment]
I think that last sentence is the actual key: all of the default formats except `byte` have the same potential behavior, if they get input that isn't pre-validated, but testing invalid inputs for those (using GET requests to a pyramid_swagger-enabled app), I get JSON schema validation errors for invalid integer and number formats.  So, it looks like formatter is expecting the schema validation to have caught the invalid date-time format.

Looking at [jsonschema._format](https://github.com/Julian/jsonschema/blob/master/jsonschema/_format.py#L172), it seems to have validation if and only if `strict_rfc3339` or `isodate` is available, which is [optional](https://github.com/Julian/jsonschema/blob/master/setup.py#L24). So, installing [strict-rfc3339](https://pypi.python.org/pypi/strict-rfc3339) should make validation fail in a more predictable way (pause...) and it does!  And removing it and installing [isodate](https://pypi.python.org/pypi/isodate) also does.

So, my originally proposed patch is not the right way to go: it seems like adding the right dependency so that jsonschema validates dates correctly is the better approach.  I think that means just changing the [dependency](../blob/master/setup.py#L33) to `jsonschema[format]>=2.5.1`—does that seem sane?

**Comment by laucia** [comment]
It seems very sane thanks for doing a pull request :)
