### ISSUE TITLE
get_op_for_request seems not very helpful?

### ISSUE THREAD

**Issue by nicksloan** [Yelp/bravado-core#92]
get_op_for_request claims that it makes server implementations very easy by letting you supply a path pattern and method to look up an op.

The thing is, a server implementation is going to have a concrete path more likely than a pattern, and the server would have to implement a look up of the operation anyway to get to the point of identifying the path pattern, at which point this work has already been done.

Am I missing something?

**Comment by analogue** [comment]
Maybe an example from pyramid_swagger would be helpful?  

https://github.com/striglia/pyramid_swagger/blob/255d429c06406ed7be45fd4089892a7c4cd5d596/pyramid_swagger/tween.py#L543

**Comment by nicksloan** [comment]
I see. pyramid_swagger verifies that it has the correct routes, but pyramid's routing machinery is still doing the actual work. I was going about this differently. In my project the routes are defined by the swagger spec, so essentially I'm building a swagger-based router. With that in mind, this method makes perfect sense, just not for my use case. Thanks for the link.
