### ISSUE TITLE
Missing support for multiple types

### ISSUE THREAD

**Issue by lanzz** [Yelp/bravado-core#94]
http://json-schema.org/latest/json-schema-validation.html#anchor79
> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

...
> An instance matches successfully if its primitive type is one of the types defined by keyword.

I take this to mean that I can use
```yaml
properties:
    foo:
        type:
            - 'string'
            - 'null'
```
But Bravado bombs:
> SwaggerMappingError: Don't know how to unmarshal value None with a type of ['string', 'null']

Unfortunately, I can't remove the `null` type here, because I _do_ get strings and nulls in that property from my backend, and validation fails for nulls; non-required properties are expected to _not exist_ in the dictionary and do not accept a `null` value.

**Comment by sjaensch** [comment]
This was already discussed e.g. in OAI/OpenAPI-Specification#458. It looks like the OpenAPI authors don't see it that way and say it's a documentation problem (i.e. it needs to be documented that OpenAPI doesn't support multiple types). Closing this issue.

**Comment by lanzz** [comment]
If I remove `null` from the types, I'm getting
> ValidationError: None is not of type 'string'
because I _am_ getting a `null` in that property. Should Bravado accept null values in non-required properties regardless of their type then?

**Comment by sjaensch** [comment]
Currently there is no good way to handle this case in bravado-core; see #47.
